### ISSUE TITLE
I Can't Access Skylake Cpu Temp

### ISSUE THREAD

**Issue by icetinturkey** [matteofabbri/HardwareProviders#1]
Hi,
Added support Skylake with OHL 0.8.0 but i still cant access temps.
![temp error 2](https://user-images.githubusercontent.com/41130134/42601812-9847de80-856f-11e8-875f-42a5a7a15d13.jpg)

**Comment by matteofabbri** [comment]
You are using an old version. There was a bug that was inducing OpCode and Ring0 to don't always open and close.

Option 1: Use the newest version
Option 2: Add those two lines on top of your code

            Ring0.Open();
            Opcode.Open();

Btw I'm working now to improve this even better I will push results in minutes

**Comment by matteofabbri** [comment]
Code updated with improved open and close.
Also for best performance use CpuCollection, I updated the Readme.

**Comment by icetinturkey** [comment]
Install-Package : Could not install package 'HardwareProviders.CPU.Standard 1.4.2'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.6.1', but the package does not contain any assembly references or content files that are compatible with that framework.

Can't installing .standart ones bro. Im tried other frameworks. Please update HardwareProviders.CPU. İts still 1.3.0.

And it doesnt work "ring open" thing.

**Comment by matteofabbri** [comment]
Standard is for Dot Net Standard (which is not the classical Dot Net) 
For DotNet you have to use HardwareProviders.CPU
Btw I reopen the issue to investigate problem on Skylake, maybe something went wrong in merging pull requests

**Comment by icetinturkey** [comment]
![hw error 2](https://user-images.githubusercontent.com/41130134/42685523-d7630dc4-869b-11e8-9ec5-4bc803f4323b.jpg)

Doesn't work anything :( Also im changed requestedExecutionLevel with highestAvailable.

**Comment by giobooo** [comment]
I'll just add a note here since it's a common problem… I can't seem to read my i7 8700k coffee lake temperatures. It works fine on other cpus.

**Comment by matteofabbri** [comment]
@giobooo Thanks guys, I came back from holidays and now I will work to fix it

**Comment by matteofabbri** [comment]
Just created the experimetal branch where the Skylake problem should be fixed.
Is not completly done yet, but enough to test if is reading values on your architecture now.
Let me know :) 

@giobooo @icetinturkey

**Comment by matteofabbri** [comment]
Now should be fixed please try it and let me know :)

**Comment by icetinturkey** [comment]
![problemsolved](https://user-images.githubusercontent.com/41130134/47170171-16c7dd00-d30e-11e8-9f89-bc8b31664741.jpg)
Problem is solved. Thanks so much.
